# Site settings
title: João Trindade Homepage
email: trindade.joao@gmail.com
url: https://joaoptrindade.com
description: "Online ramblings of Joao Trindade, an Android Developer, PhD in computer engineering and all-around geek."

author: Joao Trindade

contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 28774F #80B3FF
  secondary: 28536C #FD6E8A
  secondary-dark: 032336 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/joninvski
  - title: google-plus
    url: http://google.com/+JoaoTrindade
  - title: twitter
    url: http://twitter.com/joaotrindade
  - title: linkedin
    url: http://pt.linkedin.com/in/trindadejoao
  - title: flickr
    url: http://www.flickr.com/photos/joao_trindade

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
# markdown: redcarpet
permalink: "/:title"

plugins:
  - jekyll-sitemap
  - jemoji
  - pygments.rb	
  - jekyll-gist
